apiVersion: v1
kind: Service
metadata:
  name: fsl-challenge-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: fsl-challenge-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
    nodePort: 30080
